### PR TITLE
Uncomment `pytensor.config.compute_test_value = "raise"`

### LINKED ISSUE #93: Uncomment `pytensor.config.compute_test_value = "raise" in `conftest.py`
Due to a bug in PyMC (pymc-devs/pymc#6981), setting the option mentioned in the title caused an error in `test_marginal` for PyMC after updating to v5 (#91).
A PR fixing this (pymc-devs/pymc#6982) was merged into PyMC, but not yet released. The code below can be uncommented when the fix is released.

https://github.com/exoplanet-dev/celerite2/blob/7feb2e3366ab6a015cf8c62ec65db911faceeafe/python/test/pymc/conftest.py#L10-L11

### PR DESCRIPTION
**Pull request by vandalt**
PyMC 5.9.2 has been released with a fix, so this no longer crashes `test_marginal`. Fixes #93.

### CODE REVIEW

**Comment by dfm** [comment]
Thanks! Do you know why the tests are failing?

Should we add a lower bound here too:

https://github.com/exoplanet-dev/celerite2/blob/7feb2e3366ab6a015cf8c62ec65db911faceeafe/setup.py#L43

**Comment by vandalt** [comment]
I updated the lower bound!

I don't know why the tests are failing. They run fine locally, but there is some compilation error on the Github test environment. I ran them locally on Linux with `venv`, openblas, and I tried Python 3.10 and 3.11.

```
FAILED python/test/pymc/test_pymc_celerite2.py::test_consistency[10.5-RotationTerm-args6] - ImportError: /home/runner/.pytensor/compiledir_Linux-6.2--azure-x86_64-with-glibc2.35-x86_64-3.10.13-64/tmp5a7fpkjc/me5764f3d0dadd4197faacbf8742b57837127a6f6bbd36ab7bacfb70bd48fd2b0.so: undefined symbol: dgemm_
```

**Comment by vandalt** [comment]
I'll try installing with mamba to see if the issue still happens (suggestion from @bmorris3)

**Comment by dfm** [comment]
Looks like using a conda/mamba env does the trick, but this also points to a bug introduced in the most recent PyMC/Pytensor release (classic!) since it worked previously with pip!

I don't like using mamba for this cause it's still _far_ slower than the pip version, but we do what we need to these days :/

**Comment by dfm** [comment]
Thanks again for all your work on this, @vandalt!
